version: "3.8"

services:
  users-api:
    build: ./services/users-api
    ports:
      - "5000:5000"
  auth:
    build: ./services/auth-api
    ports:
      - "5001:5001"
    depends_on:
      - users-api
    command: npm start
